- README.md
- V/hello.v
Simple... adding a new language in two commits: 
1. adding the V program
2. adding the link to the V program to the RAEDME
> Adding the V language

- Elixir/elixir.ex
- README.md
Add hello world program written in elixir
> add elixir

- Julia/julia.jl
- README.md
Add hello world program written in julia
> add: julia hello world

- R/R.R
> Add R lang.

- Pascal/Pascal.pas
> add Pascal

- README.md
Sorry , i forgot to add them on README.md
> Adding Pascal & R in README.md

- D/Dlang.d
- README.md
add Dlang language and update README
> Add D language

- README.md
- Scala/Hello.scala
Adding the Scala-lang's hello world in two commits:
1. Adding the Scala-lang source code
2. Adding the redirection link to the Scala-lang source code to the README
> Adding the Scala-lang

- README.md
- Scss/Scss.scss
Added a new language ( Scss )
Commits : 
1. Add an Scss.scss file
2. Edit a languages list ( README.md ) and Add Scss link
> Scss language added

- CoffeScript/Coffe.coffe
- README.md
> CoffeScript lang added, and added to README.md file

- Groovy/HelloWorld.groovy
- Groovy/hello_world.groovy
- README.md
Adding a new programming language's (Groovy's) Hello World in two commits:
1. Adding two source codes (class based and script based) of the hello-world app in Groovy
2. Adding the link to Groovy source code to the README
> Adding the Groovy programming language

- Pashmak/hello.pashm
- README.md
Added [Pashmak](https://github.com/pashmaklang) Programming language
> Added Pashmak Language

- Cobra/Cobra.cobra
- Curl/Curl.CURL
- Erlang/Erlang.erl
- Hack/Hack.hh
- README.md
- Vala/Vala.vala
Added these languages:
1. Vala
2. Cobra
3. Curl
4. Erlang
5. HackLang
> Added 5 Languages

- Go-Gin/gin.go
- Makefile/hellofunc.c
- Makefile/hellomake.c
- Makefile/hellomake.h
- Makefile/makefile
- README.md
Added two more hello worlds
1. Go - Gin framework
2. Makefile with C language
> Added 2 Lang/Framework Hello world

- Octave/hello
- README.md
Two commits are made
1: Added the Octave language
2: Add Octave link to the README file
> Adding the Octave Language

- README.md
The pashmak programming language was written twice and I make it OK.
> Correcting a mistake in writing

- Clojure/ClojureLang.clj
Added Clojure Programming Language.
> Add Clojure Language

- Haskell/hello.hs
- README.md
- Tcl/hello.tcl
- Haskell --> /Haskell/hello.hs
- Tcl --> /Tcl/hello.tcl
> Add Haskell and Tcl hello world

- Flutter/main.dart
add Flutter program((write by Dart lang))
> Add Flutter program

- Haxe/HelloWorld.hx
- README.md
adding a new language in two commits:
1. Adding Haxe File
2. Adding the link to the README
> Adding Haxe Programming Language

- OCaml/hello.ml
- README.md
adding a new language in two commits:
1. adding the OCaml program
2. adding the link to the OCaml program to the README
> Adding the OCaml language 

- Pashmak/info.json
- Python/info.json
- README.md
- gen-readme.py
Actually that languages are not `Created By` someone. they added them to the list.
> Rename created by to added by

- Cow/Cow.cow
- Cow/fib.cow
- Cow/info.json
- Fortran/Fortran.F
- Fortran/info.json
- README.md
Simple... adding a new language in two commits:
adding the Fortran program
adding the link to the Fortran program to the RAEDME
> Adding Fortran Lang

- Nim/Nim.nim
- Nim/info.json
Nimlang added to languages list
> Nimlang added

- Csharp/CSharp.cs
update to  lasted version(c# 9 & .net 5)
> update to c# 9

- Go/README.md
Added installation guide for Golang
> Added installation guide for Golang

- .github/workflows/generate-readme.yml
- auto-gen.py
- tree.txt
> Fixed issue #98 auto-gen.py

- Awk/README.md
- Awk/book.md
- Awk/courses.md
- Awk/examples/helloworld.awk
- Awk/info.json
- Awk/resources.md
adding a new language in two commits:
1. Adding the Awk program
2. Adding books
3. Adding info, resources, courses, README
> Adding the Awk language

- Ktor/README.md
- Ktor/books.md
- Ktor/courses.md
- Ktor/examples/Ktor.kt
- Ktor/info.json
- Ktor/resources.md
- README.md
- tree.txt
> add hello world ktor

- Mql4/README.md
- Mql4/books.md
- Mql4/courses.md
- Mql4/examples/hello.mq4
- Mql4/info.json
- Mql4/resources.md
- Mql5/README.md
- Mql5/books.md
- Mql5/courses.md
- Mql5/examples/hello.mq5
- Mql5/info.json
- Mql5/resources.md
Hi
two languages added
1. Mql4
2. Mql5
> Adding the MetaQuotes Programming Language 

- Docker/examples/official.sh
Run this official image and remove it after.
https://hub.docker.com/_/hello-world
the command to install:
`docker pull hello-world`
> run official hello-world image

- README.md
- auto-gen.py
Instead of listing vertically, we can list horizontally.
Preview:
[A](#A) [B](#B) [C](#C) [D](#D) [E](#E) [F](#F) [G](#G) [H](#H) [J](#J) [K](#K) [L](#L) [M](#M) [N](#N) [O](#O) [P](#P) [R](#R) [S](#S) [T](#T) [V](#V) [W](#W) [Y](#Y) [Z](#Z)
> Beautify for letters list in readme

- Typescript/examples/interfaces.ts
Completes typescript lang tutorial interface section
> Adds typescript interfaces section

- README.md
- auto-gen.py
Added contributors image list
Preview:
<a href="https://github.com/BlackIQ/Hello-World/graphs/contributors"><img src="https://contrib.rocks/image?repo=BlackIQ/Hello-World" /></a>
> Added contributors image list

- V/README.md
> Add V README

- Yo/README.md
- Yo/books.md
- Yo/courses.md
- Yo/examples/Yo.yo
- Yo/info.json
- Yo/resources.md
A new programming language is Iranian
> add yo lang

- Csharp/examples/CSharp.cs
Updating the CSharp language using Top-level Statements
> Updated CSharp.cs

- Pony/README.md
- Pony/books.md
- Pony/courses.md
- Pony/examples/hello.pony
- Pony/info.json
- Pony/resources.md
> Added the pony language

- Pony/README.md
Hello, I'm so sorry. It was as if I had forgotten to write the link correctly :(
> Add https: // to the first link to make the link work

- Delphi/README.md
- Delphi/books.md
- Delphi/courses.md
- Delphi/examples/HelloWorld.dpr
- Delphi/info.json
- Delphi/resources.md
Hey, you all just missed `Delphi`   
Check it out
> Delphi Programming Language added

- Delphi/README.md
- Delphi/books.md
- Delphi/courses.md
- Delphi/examples/HelloWorld.dpr
- Delphi/info.json
- Delphi/resources.md
- Not-English/README.md
- Not-English/books.md
- Not-English/courses.md
- Not-English/examples/HelloWorld.dpr
- Not-English/examples/HelloWorld.ext
- Not-English/examples/guess_a_number.ext
- Not-English/info.json
- Not-English/resources.md
~English ("NOT English") was an esoteric attempt at using a natural language as a programming language. This repository hosts a second, revised version of the language. This updated version generalizes many language concepts and introduces a number of new features.   
More info at: https://github.com/AnotherTest/-English
Check out hello world: 
```
Display "Hello World" and a newline
```
> ~English ("NOT English") programming language

- kotlin/HellooWorld.kt
> Added kotlin language.

- Verilog/README.md
- Verilog/books.md
- Verilog/courses.md
- Verilog/examples/Hello_World.v
- Verilog/info.json
Adding a new language "Verilog"
> Adding Verilog language

- Forth/README.md
- Forth/books.md
- Forth/courses.md
- Forth/examples/Forth.fs
- Forth/info.json
- Forth/resources.md
- README.md
Hello :hand: 
I added Forth programming language.
> Forth programming language

- YO/README.md
> edit README of YO

- Rust/README.md
- Rust/books.md
Adding one online book to books and updating README of Rust.
> Updating Rust README and Books

- Java/README.md
- Java/books.md
- Java/info.json
- Kotlin/info.json
- kotlin/README.md
- kotlin/books.md
- kotlin/resources.md
Update resources of Java and Kotlin language
> Add some resource to Java and Kotlin

- Carbon/README.md
- Carbon/books.md
- Carbon/courses.md
- Carbon/examples/Fibonacci.Carbon
- Carbon/examples/HelloWorld.Carbon
- Carbon/info.json
- Carbon/resources.md
Hey BlackIQ
I've added Carbon Language Examples & some usefull links in resourses.md.
> Carbon Language

- Tornado/README.md
- Tornado/books.md
- Tornado/courses.md
- Tornado/examples/Tornado.py
- Tornado/info.json
- Tornado/resources.md
Another Pythonic framework added to list.
> Tornado framework added

- Ansible/README.md
- Ansible/books.md
- Ansible/courses.md
- Ansible/examples/hello-world.yaml
- Ansible/info.json
- Ansible/resources.md
Ansible as a one of the most common infrastructure and Pythonic tool added to list.
> Ansible added

- TODO.md
- Typescript/courses.md
- Typescript/info.json
- Typescript/resources.md
This PR adds two courses to learn typescript as well as helpful resources for learning Typescript. Updates the `info.json` to include author as creator and updates TODO to show resources and courses as `Done!`
Hacktoberfest 2022 contribution
> Adds Typescript Courses and Resources

- Emberjs/README.md
- Emberjs/books.md
- Emberjs/courses.md
- Emberjs/info.json
- Emberjs/resources.md
@BlackIQ another one for hacktoberfest adding more ember resources and courses
> Add ember courses and resources

- Emberjs/README.md
- Emberjs/books.md
- Emberjs/info.json
Adds a directory for Ember.js
Puts some data in the README.md and the books.md
Also creates the info.json file with myself added as a contributor.
Submission for hacktoberfest @BlackIQ
> Adding Ember Directory

- PureScript/README.md
- PureScript/examples/HelloWorld.purs
- PureScript/info.json
Simple... Adding a new language
1- Adding PureScript
> Pure script

- Qwik/README.md
- Qwik/books.md
- Qwik/examples/app.tsx
- Qwik/examples/entry.server.tsx
- Qwik/examples/root.tsx
- Qwik/info.json
- Qwik/resources.md
Qwik, The HTML-first framework. Instant apps of any size with ~ 1kb JS
> Add Qwik framework

- Limbo/limbo.limbo
I've added the Limbo Programing Langauge
> Added Limbo

- YAML/Yaml.yaml
> ➕ Add Yaml

- Pike/examples/Pike.pike
> ➕ Add Pike

- Zinc/zinc.zinc
> feat(language): Add Zinc language

- Java/README.md
- Java/examples/Java2.java
I have added another example in Java to print Hello World using print(), the first example used println(). I have also mentioned the difference between the two. I have also updated the readme file for the same. I would really appreciate if you merge this pull request and give it hacktoberfest label.
Thank you.
> Added another way of printing in Java.

- Java/examples/ATM.java
I made an ATM machine interface in which one can check its current balnace, the aount deposited, amount withdrawn, and one option to exit. 
Please merge ths PR under the label hactoberfest.
Thank you.
> ATM machine 

- Java/examples/NumberGame
Created a number game using Java, where a random number will be generated and the user need to guess that number. Depending upon the number of tries the user took to guess the number, he/she will get points.
Please merge ths PR under the label hacktoberfest.
Thank you.
> Created Number game in Java

- Java/examples/GradeCalculator.java
I developed a Grade Calculator System in which one can calculate the grade as per the criteria.
Please merge this PR under hactober label.
Thank you
> Grade Calculator System

- Java/examples/Patterns/Pattern1.java
- Java/examples/Patterns/Pattern2.java
- Java/examples/Patterns/Pattern3.java
- Java/examples/Patterns/Pattern4.java
- Java/examples/Patterns/Pattern5.java
- Java/examples/Patterns/Pattern6.java
- Java/examples/Patterns/Pattern7.java
- Java/examples/Patterns/Pattern8.java
Added examples of printing different star patterns in java.
> Star Patterns

- Java/examples/ATM.java
This enhanced ATM system represents a significant upgrade from a basic cash management system to a secure banking interface. The implementation focuses on user security through PIN authentication and transaction limits, while maintaining simplicity in user interaction. The system includes real-time transaction tracking with timestamps, protecting users from unauthorized access and providing detailed account activity monitoring.
> Secure and Feature-Rich ATM System with Transaction Management
